#!/bin/bash

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN


#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# store settings


#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

# Check or install docker
dockerapp_ynh_checkinstalldocker

# Check domain/path availability
dockerapp_ynh_loadvariables
ynh_webpath_available $domain $path_url
ynh_webpath_register $app $domain $path_url

#=================================================
# MODIFY A CONFIG FILE
#=================================================

dockerapp_ynh_findreplaceallvaribles

#=================================================
# COPY CONF
#=================================================

# Copy files to the right place
dockerapp_ynh_copyconf

db_name=$(ynh_sanitize_dbid --db_name=$app)
ynh_app_setting_set --app=$app --key=db_name --value=$db_name
ynh_mysql_setup_db --db_user=$db_name --db_name=$db_name

ynh_replace_string --match_string="__DB_USER__" --replace_string=$db_name --target_file=docker/run.sh
ynh_replace_string --match_string="__DB_PWD__" --replace_string="$db_pwd" --target_file=docker/run.sh
ynh_replace_string --match_string="__URL__" --replace_string="https://$domain" --target_file=docker/run.sh


#=================================================
# START AND CREATE SERVICE
#=================================================

# docker run
dockerapp_ynh_run

#=================================================
# NGINX CONFIGURATION
#=================================================

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

#=================================================
# SETUP SSOWAT
#=================================================

# Add webhook URLs to SSOwat skip list
ynh_app_setting_set --app=$app --key=skipped_uris --value="/api/webhooks/"

#=================================================
# RELOAD SSOWAT
#=================================================

# Regenerate SSOwat conf
dockerapp_ynh_reloadservices
